# Information retrieval

## Home Work #5

## Page Rank Alogrithm
### Group 1
#### Ali Mojahed - 9812762554
#### Mehrnoosh Navidimehr - 9822762119
#### Minoo Mohaghegh - 9812762270
#### Helia Ghahraman - 9822762437


In [ ]:
import numpy as np

# read data from file
with open('/content/input.txt', 'r') as f:
  data = f.read().rstrip('\n')
  data = data.split('\n#\n')

n_graphs = int(data[0])
graphs = []

for i in range(n_graphs):
  graph = [line.split(' ') for line in data[i+1].split('\n')]
  g = [list(map(int, j)) for j in graph]
  graphs.append(np.array(g))

In [ ]:
# returns the rank of page p
def page_rank(graph, p):
  d = 0.15
  n_page = graph.shape[0]
  p_rank = 0

  for i in range(n_page):
    # check if page i has a link to page p
    if(graph[i][p]):
      # number of links from page i to other pages
      n_links = 0

      for j in range(n_page):
        # check if page i has a link to page j
        if (graph[i][j]):
          n_links += 1

      p_rank += ranks[i]/n_links

  p_rank = (1-d)/n_page + d*p_rank
  return p_rank

In [ ]:
# first approach of updating pageranks
#######################################

n_iteration = 10

with open('/content/output.txt', 'w') as file:
  for i in range(n_graphs):
    print(i+1)
    file.write(f"{i+1}\n")

    n_page = graphs[i].shape[0]
    # initialize the ranks
    ranks = np.ones(n_page)

    for j in range(n_iteration):
      print(ranks)
      file.writelines(f"{ranks}\n")

      new_ranks = []
      for k in range (n_page):
        new_ranks.append(page_rank(graphs[i], k))

      # update ranks after each iteration
      ranks = new_ranks

1
[1. 1. 1. 1. 1.]
[0.295, 0.295, 0.39499999999999996, 0.44499999999999995, 0.16999999999999998]
[0.20249999999999999, 0.21187499999999998, 0.25887499999999997, 0.24674999999999997, 0.16999999999999998]
[0.19569374999999997, 0.19813124999999998, 0.22219999999999998, 0.22747499999999998, 0.16999999999999998]
[0.19385999999999998, 0.19578703124999997, 0.21879828124999998, 0.22357968749999999, 0.16999999999999998]
[0.19368991406249997, 0.19547941406249997, 0.21807645312499999, 0.22305796874999997, 0.16999999999999998]
[0.19365382265624997, 0.1954305662109375, 0.21798543886718746, 0.22297573476562496, 0.16999999999999998]
[0.19364927194335935, 0.19542330864257812, 0.21797039691406248, 0.22296385687499998, 0.16999999999999998]
[0.1936485198457031, 0.19542221524145506, 0.21796827392700194, 0.22296201614208982, 0.16999999999999998]
[0.19364841369635008, 0.1954220526847778, 0.21796794140974118, 0.22296174598256835, 0.16999999999999998]
2
[1. 1. 1.]
[0.43333333333333335, 0.35833333333333334, 0.

In [ ]:
# second approach of updating pageranks
########################################

for i in range(n_graphs):
  print(i+1)

  n_page = graphs[i].shape[0]
  # initialize the ranks
  ranks = np.ones(n_page)

  for j in range(n_iteration):
    print(ranks)

    for k in range (n_page):
      # update ranks after computing the rank of each page
      ranks[k] = page_rank(graphs[i], k)

1
[1. 1. 1. 1. 1.]
[0.295    0.242125 0.342125 0.298425 0.17    ]
[0.19985625 0.20209547 0.22975297 0.22455197 0.17      ]
[0.19423765 0.19605547 0.21825062 0.22307085 0.17      ]
[0.19366253 0.19543722 0.21798532 0.22296485 0.17      ]
[0.19364927 0.19542296 0.21796842 0.22296187 0.17      ]
[0.19364842 0.19542205 0.21796791 0.2229617  0.17      ]
[0.1936484  0.19542203 0.21796789 0.2229617  0.17      ]
[0.19364839 0.19542202 0.21796788 0.2229617  0.17      ]
[0.19364839 0.19542202 0.21796788 0.2229617  0.17      ]
2
[1. 1. 1.]
[0.43333333 0.31583333 0.36320833]
[0.33781458 0.30866943 0.35496984]
[0.33657881 0.30857674 0.35486326]
[0.33656282 0.30857554 0.35486188]
[0.33656261 0.30857553 0.35486186]
[0.33656261 0.30857553 0.35486186]
[0.33656261 0.30857553 0.35486186]
[0.33656261 0.30857553 0.35486186]
[0.33656261 0.30857553 0.35486186]
